server.port=8020

server.servlet.context-path=/jscash

 #Oracle settings ZUHAIR LAPTOP
spring.datasource.url=jdbc:oracle:thin:@77.68.88.211:1521/laprod.online-server.cloud
spring.datasource.username=JS_CASH
spring.datasource.password=CMS
spring.datasource.driver-class-oracle.jdbc.driver.OracleDriver
# Username: JS_CASH
# Password: CMS
# IP: 77.68.88.211
# Service Name: laprod.online-server.cloud

  #Oracle settings ZUHAIR LAPTOP
#spring.datasource.url=jdbc:oracle:thin:@20.212.202.66:1521/orclpdb1
#spring.datasource.username=JS_CMS
#spring.datasource.password=Cms_12345
#spring.datasource.driver-class-oracle.jdbc.driver.OracleDriver


#  #Oracle settings ZUHAIR LAPTOP
#spring.datasource.url=jdbc:oracle:thin:@20.212.202.66:1521/orclpdb1
#spring.datasource.username=JS_CMS
#spring.datasource.password=Cms_12345
#spring.datasource.driver-class-oracle.jdbc.driver.OracleDriver


spring.mvc.pathmatch.matching-strategy=ant_path_matcher

# logging
logging.level.org.hibernate.SQL=trace




length.rrn = 9

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.ws.client.MessageTracing.sent=DEBUG
logging.level.org.springframework.ws.server.MessageTracing.sent=DEBUG
logging.level.org.springframework.ws.client.MessageTracing.received=TRACE
logging.level.org.springframework.ws.server.MessageTracing.received=TRACE
