server.port=8080

server.servlet.context-path=/jscash

#Oracle settings ZUHAIR LAPTOP
spring.datasource.url=jdbc:oracle:thin:@20.212.202.66:1521/orclpdb1
spring.datasource.username=JS_CMS
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-oracle.jdbc.driver.OracleDriver


spring.mvc.pathmatch.matching-strategy=ant_path_matcher

# logging
logging.level.org.hibernate.SQL=trace

spring.datasource.hikari.connectionTimeout=30000 
spring.datasource.hikari.idleTimeout=600000 
spring.datasource.hikari.maxLifetime=1800000 


length.rrn = 9

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.ws.client.MessageTracing.sent=DEBUG
logging.level.org.springframework.ws.server.MessageTracing.sent=DEBUG
logging.level.org.springframework.ws.client.MessageTracing.received=TRACE
logging.level.org.springframework.ws.server.MessageTracing.received=TRACE
