-- DFS CMS workflow side tables (additive — do not ALTER TBL_TRANS_HEAD)
-- Run as JS_CASH (or schema owner)

CREATE SEQUENCE TBL_CMS_TXN_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE TBL_CMS_TXN_AUDIT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE TBL_CMS_BENEFICIARY_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE TBL_CMS_MATRIX_BAND_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE TBL_CMS_TXN (
  TXN_ID              NUMBER(19) PRIMARY KEY,
  COMPANY_ID          NUMBER(19) NOT NULL,
  PRODUCT_CODE        VARCHAR2(32) NOT NULL,
  STATUS              VARCHAR2(32) NOT NULL,
  AMOUNT              NUMBER(18,2) NOT NULL,
  CURRENCY            VARCHAR2(8) DEFAULT 'PKR',
  CUST_REF            VARCHAR2(128),
  DEBIT_ACCOUNT       VARCHAR2(64),
  BEN_BANK_NAME       VARCHAR2(128),
  BEN_BANK_IMD        VARCHAR2(32),
  BEN_IBAN            VARCHAR2(34),
  BEN_TITLE           VARCHAR2(256),
  BEN_PHONE           VARCHAR2(32),
  SCHEDULE_DATE       DATE,
  TRANS_HEAD_ID       NUMBER(19),
  IDEMPOTENCY_KEY     VARCHAR2(64),
  NEXT_APPROVER_EMAIL VARCHAR2(128),
  NEXT_APPROVER_MOBILE VARCHAR2(32),
  STOP_REASON         VARCHAR2(512),
  APPROVALS_REQUIRED  NUMBER(3) DEFAULT 1,
  APPROVALS_DONE      NUMBER(3) DEFAULT 0,
  MAKER_USER_ID       NUMBER(19),
  AUTH_USER_ID        NUMBER(19),
  RELEASE_USER_ID     NUMBER(19),
  MAKER_AT            TIMESTAMP,
  AUTH_AT             TIMESTAMP,
  RELEASE_AT          TIMESTAMP,
  PAID_AT             TIMESTAMP,
  MOCK_MODE           CHAR(1) DEFAULT 'Y',
  PAYLOAD_JSON        CLOB,
  INSTRUMENT_NO       VARCHAR2(64),
  CREATEDATE          TIMESTAMP DEFAULT SYSTIMESTAMP,
  LASTUPDATEDATE      TIMESTAMP
);

CREATE INDEX IDX_CMS_TXN_CO_ST ON TBL_CMS_TXN (COMPANY_ID, STATUS);
CREATE INDEX IDX_CMS_TXN_SCHED ON TBL_CMS_TXN (SCHEDULE_DATE, STATUS);
CREATE UNIQUE INDEX IDX_CMS_TXN_IDEMP ON TBL_CMS_TXN (IDEMPOTENCY_KEY);

CREATE TABLE TBL_CMS_TXN_AUDIT (
  AUDIT_ID     NUMBER(19) PRIMARY KEY,
  TXN_ID       NUMBER(19) NOT NULL,
  COMPANY_ID   NUMBER(19) NOT NULL,
  FROM_STATUS  VARCHAR2(32),
  TO_STATUS    VARCHAR2(32) NOT NULL,
  ACTION       VARCHAR2(64) NOT NULL,
  USER_ID      NUMBER(19),
  COMMENTS     VARCHAR2(512),
  CREATEDATE   TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE INDEX IDX_CMS_AUD_TXN ON TBL_CMS_TXN_AUDIT (TXN_ID);

CREATE TABLE TBL_CMS_BENEFICIARY (
  BENEFICIARY_ID NUMBER(19) PRIMARY KEY,
  COMPANY_ID     NUMBER(19) NOT NULL,
  BANK_NAME      VARCHAR2(128),
  BANK_IMD       VARCHAR2(32),
  IBAN           VARCHAR2(34) NOT NULL,
  ACCOUNT_TITLE  VARCHAR2(256),
  PHONE          VARCHAR2(32),
  LOCKED         CHAR(1) DEFAULT 'N',
  ACTIVE         CHAR(1) DEFAULT 'Y',
  CREATEUSER     NUMBER(19),
  CREATEDATE     TIMESTAMP DEFAULT SYSTIMESTAMP,
  LASTUPDATEDATE TIMESTAMP
);

CREATE UNIQUE INDEX IDX_CMS_BENE_CO_IBAN ON TBL_CMS_BENEFICIARY (COMPANY_ID, IBAN);

CREATE TABLE TBL_CMS_MATRIX_BAND (
  BAND_ID            NUMBER(19) PRIMARY KEY,
  COMPANY_ID         NUMBER(19),
  PRODUCT_CODE       VARCHAR2(32) NOT NULL,
  FROM_AMOUNT        NUMBER(18,2) NOT NULL,
  TO_AMOUNT          NUMBER(18,2) NOT NULL,
  APPROVALS_REQUIRED NUMBER(3) DEFAULT 1
);

INSERT INTO TBL_CMS_MATRIX_BAND (BAND_ID, COMPANY_ID, PRODUCT_CODE, FROM_AMOUNT, TO_AMOUNT, APPROVALS_REQUIRED)
VALUES (TBL_CMS_MATRIX_BAND_SEQ.NEXTVAL, NULL, 'IBFT', 0, 50000, 1);
INSERT INTO TBL_CMS_MATRIX_BAND (BAND_ID, COMPANY_ID, PRODUCT_CODE, FROM_AMOUNT, TO_AMOUNT, APPROVALS_REQUIRED)
VALUES (TBL_CMS_MATRIX_BAND_SEQ.NEXTVAL, NULL, 'IBFT', 50000.01, 999999999, 2);

COMMIT;
